"""empty message

Revision ID: 8235b72565d5
Revises: 
Create Date: 2018-07-19 02:30:03.756261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8235b72565d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('escolaridade', sa.Enum('superior_completo', 'superior_incompleto', 'medio_completo', 'medio_incompleto', 'fundamental_completo', 'fundamental_incompleto', name='enumescolaridade'), nullable=True),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'divorciado', 'separado', 'viuvo', name='enumestadocivil'), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', name='enumsexo'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formacao_academica', sa.String(length=100), nullable=True),
    sa.Column('cursos_realizados', sa.Text(), nullable=True),
    sa.Column('experiencia_profissional', sa.Text(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('id_candidato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_candidato'], ['candidato.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anuncio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('jornada', sa.Enum('integral', 'meio_periodo', 'estagio', 'outra', name='enumjornada'), nullable=True),
    sa.Column('qtde_vagas', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pub', sa.DateTime(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncio')
    op.drop_table('curriculo')
    op.drop_table('categoria')
    op.drop_table('empresa')
    op.drop_table('candidato')
    # ### end Alembic commands ###
